excluded:
- SeSACMarket/*/AppDelegate.swift
- SeSACMarket/*/SceneDelegate.swift

disabled_rules:
- xctfail_message
- function_parameter_count
- legacy_constructor
- nesting
- todo
- file_length

line_length: 99
